class ConfigPersonagem:
    SCREEN_HEIGHT = 600
    SCREEN_WIDTH = 1000
    FPS = 60
    LARGURA_PERSONAGEM = 0.1 * SCREEN_WIDTH
    ALTURA_PERSONAGEM = 0.1 * SCREEN_HEIGHT
    TAMANHO = (LARGURA_PERSONAGEM, ALTURA_PERSONAGEM)
    DEFAULT_LARGURA = TAMANHO[0]
    DEFAULT_ALTURA = TAMANHO[1]
    TAMANHO_TIRO = ((0.3 * LARGURA_PERSONAGEM), (0.3 * ALTURA_PERSONAGEM ))
    POSX_PERSONAGEM = SCREEN_WIDTH / 2 
    POSY_PERSONAGEM = SCREEN_HEIGHT / 2  
    
    
